
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox8;

	private global::Gtk.Label label2;

	private global::Gtk.Entry Pantalla;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button vaciar;

	private global::Gtk.Button borrar;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Button siete;

	private global::Gtk.Button ocho;

	private global::Gtk.Button nueve;

	private global::Gtk.Button barra;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Button cuatro;

	private global::Gtk.Button cinco;

	private global::Gtk.Button seis;

	private global::Gtk.Button multiplicar;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Button uno;

	private global::Gtk.Button dos;

	private global::Gtk.Button tres;

	private global::Gtk.Button resta;

	private global::Gtk.HBox hbox11;

	private global::Gtk.Button punto;

	private global::Gtk.Button cero;

	private global::Gtk.Button igual;

	private global::Gtk.Button suma;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Calculadora");
		this.vbox8.Add(this.label2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.Pantalla = new global::Gtk.Entry();
		this.Pantalla.HeightRequest = 50;
		this.Pantalla.CanFocus = true;
		this.Pantalla.Name = "Pantalla";
		this.Pantalla.IsEditable = true;
		this.Pantalla.InvisibleChar = '•';
		this.vbox8.Add(this.Pantalla);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.Pantalla]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.vaciar = new global::Gtk.Button();
		this.vaciar.WidthRequest = 200;
		this.vaciar.HeightRequest = 40;
		this.vaciar.CanFocus = true;
		this.vaciar.Name = "vaciar";
		this.vaciar.UseUnderline = true;
		this.vaciar.Label = global::Mono.Unix.Catalog.GetString("Vaciar");
		this.hbox7.Add(this.vaciar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vaciar]));
		w3.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.borrar = new global::Gtk.Button();
		this.borrar.WidthRequest = 40;
		this.borrar.CanFocus = true;
		this.borrar.Name = "borrar";
		this.borrar.UseUnderline = true;
		this.borrar.Label = global::Mono.Unix.Catalog.GetString("C");
		this.hbox7.Add(this.borrar);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.borrar]));
		w4.Position = 1;
		this.vbox8.Add(this.hbox7);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox7]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.siete = new global::Gtk.Button();
		this.siete.WidthRequest = 75;
		this.siete.HeightRequest = 40;
		this.siete.CanFocus = true;
		this.siete.Name = "siete";
		this.siete.UseUnderline = true;
		this.siete.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox8.Add(this.siete);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.siete]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.ocho = new global::Gtk.Button();
		this.ocho.WidthRequest = 75;
		this.ocho.HeightRequest = 40;
		this.ocho.CanFocus = true;
		this.ocho.Name = "ocho";
		this.ocho.UseUnderline = true;
		this.ocho.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox8.Add(this.ocho);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.ocho]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.nueve = new global::Gtk.Button();
		this.nueve.WidthRequest = 75;
		this.nueve.HeightRequest = 40;
		this.nueve.CanFocus = true;
		this.nueve.Name = "nueve";
		this.nueve.UseUnderline = true;
		this.nueve.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox8.Add(this.nueve);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.nueve]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.barra = new global::Gtk.Button();
		this.barra.WidthRequest = 75;
		this.barra.HeightRequest = 40;
		this.barra.CanFocus = true;
		this.barra.Name = "barra";
		this.barra.UseUnderline = true;
		this.barra.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox8.Add(this.barra);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.barra]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox8.Add(this.hbox8);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox8]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.cuatro = new global::Gtk.Button();
		this.cuatro.WidthRequest = 75;
		this.cuatro.HeightRequest = 40;
		this.cuatro.CanFocus = true;
		this.cuatro.Name = "cuatro";
		this.cuatro.UseUnderline = true;
		this.cuatro.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox9.Add(this.cuatro);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.cuatro]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.cinco = new global::Gtk.Button();
		this.cinco.WidthRequest = 75;
		this.cinco.HeightRequest = 40;
		this.cinco.CanFocus = true;
		this.cinco.Name = "cinco";
		this.cinco.UseUnderline = true;
		this.cinco.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox9.Add(this.cinco);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.cinco]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.seis = new global::Gtk.Button();
		this.seis.WidthRequest = 75;
		this.seis.HeightRequest = 40;
		this.seis.CanFocus = true;
		this.seis.Name = "seis";
		this.seis.UseUnderline = true;
		this.seis.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox9.Add(this.seis);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.seis]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.multiplicar = new global::Gtk.Button();
		this.multiplicar.WidthRequest = 75;
		this.multiplicar.HeightRequest = 40;
		this.multiplicar.CanFocus = true;
		this.multiplicar.Name = "multiplicar";
		this.multiplicar.UseUnderline = true;
		this.multiplicar.Label = global::Mono.Unix.Catalog.GetString("*");
		this.hbox9.Add(this.multiplicar);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.multiplicar]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox8.Add(this.hbox9);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox9]));
		w15.Position = 4;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.uno = new global::Gtk.Button();
		this.uno.WidthRequest = 75;
		this.uno.HeightRequest = 40;
		this.uno.CanFocus = true;
		this.uno.Name = "uno";
		this.uno.UseUnderline = true;
		this.uno.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox10.Add(this.uno);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.uno]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.dos = new global::Gtk.Button();
		this.dos.WidthRequest = 75;
		this.dos.HeightRequest = 40;
		this.dos.CanFocus = true;
		this.dos.Name = "dos";
		this.dos.UseUnderline = true;
		this.dos.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox10.Add(this.dos);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.dos]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.tres = new global::Gtk.Button();
		this.tres.WidthRequest = 75;
		this.tres.HeightRequest = 40;
		this.tres.CanFocus = true;
		this.tres.Name = "tres";
		this.tres.UseUnderline = true;
		this.tres.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox10.Add(this.tres);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.tres]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.resta = new global::Gtk.Button();
		this.resta.WidthRequest = 75;
		this.resta.HeightRequest = 40;
		this.resta.CanFocus = true;
		this.resta.Name = "resta";
		this.resta.UseUnderline = true;
		this.resta.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox10.Add(this.resta);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.resta]));
		w19.Position = 3;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox8.Add(this.hbox10);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox10]));
		w20.Position = 5;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.punto = new global::Gtk.Button();
		this.punto.WidthRequest = 75;
		this.punto.HeightRequest = 40;
		this.punto.CanFocus = true;
		this.punto.Name = "punto";
		this.punto.UseUnderline = true;
		this.punto.Label = global::Mono.Unix.Catalog.GetString(".");
		this.hbox11.Add(this.punto);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.punto]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.cero = new global::Gtk.Button();
		this.cero.WidthRequest = 75;
		this.cero.HeightRequest = 40;
		this.cero.CanFocus = true;
		this.cero.Name = "cero";
		this.cero.UseUnderline = true;
		this.cero.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox11.Add(this.cero);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.cero]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.igual = new global::Gtk.Button();
		this.igual.WidthRequest = 75;
		this.igual.HeightRequest = 40;
		this.igual.CanFocus = true;
		this.igual.Name = "igual";
		this.igual.UseUnderline = true;
		this.igual.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox11.Add(this.igual);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.igual]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.suma = new global::Gtk.Button();
		this.suma.WidthRequest = 75;
		this.suma.HeightRequest = 40;
		this.suma.CanFocus = true;
		this.suma.Name = "suma";
		this.suma.UseUnderline = true;
		this.suma.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox11.Add(this.suma);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.suma]));
		w24.Position = 3;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox8.Add(this.hbox11);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox11]));
		w25.Position = 6;
		w25.Expand = false;
		w25.Fill = false;
		this.Add(this.vbox8);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 318;
		this.DefaultHeight = 309;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.vaciar.Clicked += new global::System.EventHandler(this.OnVaciarClicked);
		this.borrar.Clicked += new global::System.EventHandler(this.OnBorrarClicked);
		this.siete.Clicked += new global::System.EventHandler(this.OnSieteClicked);
		this.ocho.Clicked += new global::System.EventHandler(this.OnOchoClicked);
		this.nueve.Clicked += new global::System.EventHandler(this.OnNueveClicked);
		this.barra.Clicked += new global::System.EventHandler(this.OnBarraClicked);
		this.cuatro.Clicked += new global::System.EventHandler(this.OnCuatroClicked);
		this.cinco.Clicked += new global::System.EventHandler(this.OnCincoClicked);
		this.seis.Clicked += new global::System.EventHandler(this.OnSeisClicked);
		this.multiplicar.Clicked += new global::System.EventHandler(this.OnMultiplicarClicked);
		this.uno.Clicked += new global::System.EventHandler(this.OnUnoClicked);
		this.dos.Clicked += new global::System.EventHandler(this.OnDosClicked);
		this.tres.Clicked += new global::System.EventHandler(this.OnTresClicked);
		this.resta.Clicked += new global::System.EventHandler(this.OnRestaClicked);
		this.punto.Clicked += new global::System.EventHandler(this.OnPuntoClicked);
		this.cero.Clicked += new global::System.EventHandler(this.OnCeroClicked);
		this.igual.Clicked += new global::System.EventHandler(this.OnIgualClicked);
		this.suma.Clicked += new global::System.EventHandler(this.OnSumaClicked);
	}
}
